package com.zx.landdisaster.module.groupdefense.bean

import java.io.Serializable

/**
 * Updated by FANGYI on 2019-04-26
 */
data class GroupDefenceBean(var address: String,
                            var alarmphone: String,
                            var areacode: String,
                            var areas: String,
                            var areastation: String,
                            var behindedgeheight: String,
                            var controlgrade: String,
                            var controlstate: String,
                            var controlsystem: String,
                            var curstablestatus: String,
                            var damagedhousedoor: String,
                            var damagedhouseroom: String,
                            var dangerousrank: String,
                            var deathcount: String,
                            var destroyedcanal: String,
                            var destroyedobj: String,
                            var destroyedroad: String,
                            var destroyshome: String,
                            var destroyshouse: String,
                            var destroytime: String,
                            var directloss: String,
                            var disastegrad: String,
                            var disasterstatus: String,
                            var elevation: String,
                            var filltabledate: String,
                            var filltablepeople: String,
                            var frontedgeheight: String,
                            var geomorphictype: String,
                            var happendtime: String,
                            var hasterminal: String,
                            var hiddenpoint: String,
                            var housethreat: String,
                            var indirectloss: String,
                            var indoorcode: String,
                            var injuredperson: String,
                            var latitude: Double,
                            var lnvestigationtime: String,
                            var longitude: Double,
                            var mainaffectobj: String,
                            var modulesystem: String,
                            var monimeasuretype: String,
                            var monitormass: String,
                            var monitormeasure: String,
                            var monitorsuggested: String,
                            var name: String,
                            var note: String,
                            var otherharms: String,
                            var outdoorcode: String,
                            var outdoorrecord: String,
                            var phone: String,
                            var pkiaa: String,
                            var preventionmethod: String,
                            var preventionplan: String,
                            var preventionsuggested: String,
                            var prevmeasuretype: String,
                            var proegumenalcause: String,
                            var reservoirregion: String,
                            var scalelevel: String,
                            var slidevolume: String,
                            var stabletrend: String,
                            var storagetime: String,
                            var surveydept: String,
                            var surveyheader: String,
                            var tdimageurl: String,
                            var threatencentiare: String,
                            var threatenobj: String,
                            var threatenpro: String,
                            var threatenroom: String,
                            var transtroublehide: String,
                            var trappedunm: String,
                            var type: String,
                            var verifypeople: String,
                            var videoname: String,
                            var villageheader: String,
                            var wadingproperty: String,
                            var x: String,
                            var y: String,
                            var macropatrolset: Macropatrolset,
                            var disvolume: String,
                            var monimeasuretypeDesc: String,
                            var dangerousrankDesc: String,
                            var monitorsuggestedDesc: String,
                            var prevmeasuretypeDesc: String,
                            var destroyedobjDesc: String,
                            var disastegradDesc: String,
                            var monitormeasureDesc: String,
                            var threatenobjDesc: String,
                            var scalelevelDesc: String,
                            var monitorpointinfo: List<Monitorpointinfo>):Serializable {
    data class Macropatrolset(var bluealert: String,
                              var bluealertnum: String,
                              var legalradius: Int,
                              var name: String,
                              var orangealert: String,
                              var orangealertnum: String,
                              var pkiaa: String,
                              var pkiaaname: String,
                              var redalert: String,
                              var redalertnum: String,
                              var remarks: String,
                              var setid: String,
                              var yellowalert: String,
                              var yellowalertnum: String):Serializable

    data class Monitorpointinfo(var alertinitialtotal: String,
                                var bluealertnum: String,
                                var bluealertset: String,
                                var bluealertstore: String,
                                var createpointtime: String,
                                var damage: String,
                                var dimension: String,
                                var direction: String,
                                var legal: String,
                                var legalredius: Int,
                                var mpid: String,
                                var name: String,
                                var note: String,
                                var orangealertnum: String,
                                var orangealertset: String,
                                var orangealertstore: String,
                                var pkiaa: String,
                                var pkiaaname: String,
                                var redalertnum: String,
                                var redalertset: String,
                                var redalertstore: String,
                                var runtime: String,
                                var type: String,
                                var yellowalertnum: String,
                                var yellowalertset: String,
                                var yellowalertstore: String):Serializable
}

