package com.zx.landdisaster.module.areamanager.bean

/**
 * Updated by dell on 2019-04-17
 */
data class AreaManagerBean(var address: String,
                           var areacode: String,
                           var assessdata: String,
                           var dangerousrank: String,
                           var deathcount: String?,
                           var destroyshouse: String,
                           var directloss: String,
                           var disastegrad: String,
                           var disasterdata: String,
                           var disasterstatus: String,
                           var disvolume: String,
                           var elevation: String,
                           var emergencydata: String,
                           var farmdestroy: String,
                           var filltabledate: String,
                           var filltablepeople: String,
                           var hiddenpoint: String,
                           var housethreat: String,
                           var indoorcode: String,
                           var latitude: Double,
                           var longitude: Double,
                           var monimeasuretype: String,
                           var monitormass: String,
                           var monitormeasure: String,
                           var monitorsuggested: String,
                           var name: String,
                           var otherharms: String,
                           var outdoorcode: String,
                           var phone: String,
                           var pkiaa: String,
                           var preventionmethod: String,
                           var preventionplan: String,
                           var preventionsuggested: String,
                           var prevmeasuretype: String,
                           var slidevolume: String,
                           var sreportsdata: String,
                           var storagetime: String,
                           var surveydept: String,
                           var surveyheader: String,
                           var threatenobj: String,
                           var threatenpro: Int,
                           var transinterrupt: String,
                           var transtroublehide: String,
                           var trappedunm: Int,
                           var type: String,
                           var verifypeople: String,
                           var videoname: String,
                           var villageheader: String,
                           var x: Int,
                           var y: Int)