package com.zx.landdisaster.module.disaster.bean

import java.io.Serializable

/**
 * Updated by dell on 2019-04-02
 */
data class HiddenDetailBean(var address: String?,
                            var areacode: String?,
                            var controlgrade: String?,
                            var controlstate: String?,
                            var controlsystem: String?,
                            var curstablestatus: String?,
                            var damagedhouseroom: String?,
                            var dangerousrank: String?,
                            var dangerousrankDesc: String?,
                            var deathcount: String?,
                            var destroyedcanal: String?,
                            var destroyedobj: String?,
                            var destroyedroad: String?,
                            var destroyshouse: String?,
                            var directloss: String?,
                            var disastegrad: String?,
                            var disastegradDesc: String?,
                            var disasterstatus: String?,
                            var disvolume: String?,
                            var elevation: String?,
                            var farmdestroy: String?,
                            var filltabledate: String?,
                            var filltablepeople: String?,
                            var geomorphictype: String?,
                            var happendtime: String?,
                            var hiddenpoString: String?,
                            var housethreat: String?,
                            var indirectloss: String?,
                            var indoorcode: String?,
                            var injuredperson: String?,
                            var longitude: Double?,
                            var latitude: Double?,
                            var lnvestigationtime: String?,
                            var Stringitude: String?,
                            var modulesystem: String?,
                            var monimeasuretype: String?,
                            var monitormass: String?,
                            var monitormeasure: String?,
                            var monitorsuggested: String?,
                            var name: String?,
                            var otherharms: String?,
                            var outdoorcode: String?,
                            var outdoorrecord: String?,
                            var phone: String?,
                            var pkiaa: String?,
                            var preventionmethod: String?,
                            var preventionplan: String?,
                            var preventionsuggested: String?,
                            var prevmeasuretype: String?,
                            var proegumenalcause: String?,
                            var reservoirregion: String?,
                            var scalelevel: String?,
                            var scalelevelDesc: String?,
                            var slidevolume: String?,
                            var stabletrend: String?,
                            var storagetime: String?,
                            var surveydept: String?,
                            var surveyheader: String?,
                            var tdimageurl: String?,
                            var threatencentiare: String?,
                            var threatenobj: String?,
                            var threatenobjDesc: String?,
                            var threatenpro: String?,
                            var threatenroom: String?,
                            var transStringerrupt: String?,
                            var transtroublehide: String?,
                            var trappedunm: String?,
                            var type: String?,
                            var verifypeople: String?,
                            var videoname: String?,
                            var villageheader: String?,
                            var wadingproperty: String?,
                            var x: String?,
                            var y: String?,
                            var overlimgprogress: String) : Serializable {
    fun getScaleLevelString(): String = when (scalelevel) {
        "A" -> "特大型"
        "B" -> "大型"
        "C" -> "小型"
        "D" -> "中型"
        else -> ""
    }
}